---
- name: goodstuff
  hosts: all
  user: pi
  become: yes
  become_method: sudo

  tasks:
    - name: install good stuff
      apt: pkg={{item}} state=present
      with_items:
        - rsync
        - htop
        - screen
